SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL';

ALTER TABLE `Books` 
DROP FOREIGN KEY `BOOK_PUBLISHER`,
DROP FOREIGN KEY `BOOK_SERIES`;

CREATE TABLE IF NOT EXISTS `BookLocations` (
  `bookId` INT(10) UNSIGNED NOT NULL,
  `locationId` INT(10) UNSIGNED NOT NULL,
  INDEX `STORELOCATION_LOCATION_idx` (`locationId` ASC),
  INDEX `BOOKLOCATION_BOOK_idx` (`bookId` ASC),
  CONSTRAINT `BOOKLOCATION_LOCATION`
    FOREIGN KEY (`locationId`)
    REFERENCES `Locations` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `BOOKLOCATION_BOOK`
    FOREIGN KEY (`bookId`)
    REFERENCES `Books` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE TABLE IF NOT EXISTS `BookStores` (
  `bookId` INT(10) UNSIGNED NOT NULL,
  `storeId` INT(10) UNSIGNED NOT NULL,
  INDEX `BOOKSTORE_BOOK_idx` (`bookId` ASC),
  INDEX `BOOKSTORE_STORE_idx` (`storeId` ASC),
  CONSTRAINT `BOOKSTORE_BOOK`
    FOREIGN KEY (`bookId`)
    REFERENCES `Books` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `BOOKSTORE_STORE`
    FOREIGN KEY (`storeId`)
    REFERENCES `Stores` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

ALTER TABLE `Books` 
CHANGE COLUMN `seriesId` `seriesId` INT(11) UNSIGNED NULL DEFAULT NULL COMMENT 'Book series' ,
CHANGE COLUMN `publisherId` `publisherId` INT(11) UNSIGNED NULL DEFAULT NULL COMMENT 'Publisher' ,
CHANGE COLUMN `title` `title` VARCHAR(255) NULL DEFAULT NULL COMMENT 'Title' ,
CHANGE COLUMN `pages` `pages` INT(4) NULL DEFAULT NULL COMMENT 'Number of pages' ,
CHANGE COLUMN `description` `description` LONGTEXT NULL DEFAULT NULL COMMENT 'Book description' ,
CHANGE COLUMN `binding` `binding` ENUM('Hardcover','Softcover') NOT NULL DEFAULT 'Hardcover' COMMENT 'Book binding' ,
CHANGE COLUMN `physicalForm` `physicalForm` ENUM('Book','Manuscript','Journal','CD/DVD','Other') NOT NULL DEFAULT 'Book' COMMENT 'Physical form of book' ,
CHANGE COLUMN `size` `size` ENUM('Medium','Large','Huge','Small','Tiny') NOT NULL DEFAULT 'Medium' COMMENT 'Book size' ,
CHANGE COLUMN `type` `type` ENUM('Standard','Digital') NOT NULL DEFAULT 'Standard' COMMENT 'Type of book' ,
ADD COLUMN `eBookId` INT(10) UNSIGNED NULL DEFAULT NULL AFTER `coverId`,
ADD COLUMN `bookSN` VARCHAR(50) NULL DEFAULT NULL AFTER `eBookId`,
ADD UNIQUE INDEX `bookSN_UNIQUE` (`bookSN` ASC),
ADD INDEX `BOOK_EBOOK_idx` (`eBookId` ASC);

CREATE TABLE IF NOT EXISTS `DatabaseVersion` (
  `version` INT(11) UNSIGNED NOT NULL,
  PRIMARY KEY (`version`),
  UNIQUE INDEX `version_UNIQUE` (`version` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE TABLE IF NOT EXISTS `ElectronicBooks` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `path` VARCHAR(300) NOT NULL,
  `title` VARCHAR(100) NULL DEFAULT NULL,
  `uploadingDateTime` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `eBooks_UNIQUE` (`id` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE TABLE IF NOT EXISTS `Locations` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `storeId` INT(10) UNSIGNED NOT NULL,
  `name` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `LOCATION_STORE_idx` (`storeId` ASC),
  CONSTRAINT `LOCATION_STORE`
    FOREIGN KEY (`storeId`)
    REFERENCES `Stores` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

ALTER TABLE `Publishers` 
ADD COLUMN `description` LONGTEXT NULL DEFAULT NULL AFTER `name`;

CREATE TABLE IF NOT EXISTS `Stores` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

ALTER TABLE `Books` 
ADD CONSTRAINT `BOOK_EBOOK`
  FOREIGN KEY (`eBookId`)
  REFERENCES `ElectronicBooks` (`id`)
  ON DELETE SET NULL
  ON UPDATE SET NULL,
ADD CONSTRAINT `BOOK_PUBLISHER`
  FOREIGN KEY (`publisherId`)
  REFERENCES `Publishers` (`id`)
  ON DELETE SET NULL
  ON UPDATE SET NULL,
ADD CONSTRAINT `BOOK_SERIES`
  FOREIGN KEY (`seriesId`)
  REFERENCES `Series` (`id`)
  ON DELETE SET NULL
  ON UPDATE SET NULL;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
